#!/usr/bin/env python3
"""Installed entry for ``ros2 run gp7_vision_gazebo_bridge box_spawn_bridge_node``."""

import sys

from gp7_vision_gazebo_bridge.box_spawn_bridge_node import main


if __name__ == "__main__":
    main(sys.argv)

